PROMPTS = [
    "",
    "",
    "You are a dog. Your human left at 12:00. It is now 12:01. You are certain your human must be in great peril, for they have not returned. Action must be taken.",
    "",
    "What is(are) your New Year Resolution(s)? How do you ensure that you successfully achieve it(them)?",
    "Write a diary entry for today.",
    "You suddenly wake up in a summer day of June 1st 1970 where you're currently located. Assuming you retain all your memories, what will you do?",
    "What did you dream about last night?",
    "You go to the mall one a usual day, all the shops are open but there is not a single person in sight, not even staffs and employees. What could have happened?",
    "Write about your favourite movie from last year.",
    "It is the year 2200, Samsung releases a new smart refridgerator, what features does it have?",
    "You are the last remaining cat in the world. What is going on in your head?",
    "Write a diary entry for today.",
    "What are some of the things you would never cheap out on?",
    "Open the photo gallery on your phone, and write a fictional story based on the last 4 pictures taken.",
    "It is now the yer 2050 and the app TikTok is used professionally for your job interviews, what do you do to impress your recruiters?",
    "A pair of parents wants a second child, should the decision must be approved by the first child first?",
    "Suppose you could upload your entire memory to the cloud when you die, would you do it? Why or why not?",
    "In your opinion, what is the meme of the last decade (2009 to 2019)?",
    "Write a diary entry for today.",
    "What is one modern technology you're grateful about?",
    "You just won 200 million dollars, what will you do?",
    "Malaysian Airlines MH-370, an airliner that was lost 6 years ago and never found, lands in Beijing today. All passengers on-board are unaware of their supposed disappearance. To them, this felt like a normal flight.",
    "It has been 10 years since Thanos snapped half of the population in the universe and you survived, what is the world like now?",
    "Describe one time when you felt emotionally touched.",
    "Write a diary entry for today.",
    "You are the most wanted man in the world for 24 hours, whoever kills you gets 1 billion dollars. But if you survive, you get 1 billion dollars. You have 24 hours prior to that to prepare, what will you do?",
    "Which instrument do you really want to learn and why?",
    "What do you carry with you everyday and how does that reflect you as a person?",
    "You and your SO swaps body for a day.",
    "You're hosting your own podcast, what is it about?",
    "It is the year 3000 and Apple announces the new iPhone XXXX, what features does it have?",
    "Write a diary entry for today.",
    "Write a poetry about the adversities you faced in your life.",
    "What trend do you think is overrated and that you just don't understand why it's popular?",
    "In a parallel universe, being hetrosexual is actually illegal.",
    "Write a character-select screen of yourself (including stats, buffs, debuffs, abilities, and ultimates)",
    "Talk about a song that best relate to you. How does this song help define or inspire you?",
    "Suppose your brain works like computer storage and is now running out of memory, what would you delete to make room for new memory?",
    "At the end of the movie Inception, do you think the main character Dom is dreaming or in real life?",
    "Should human cloning be legal for everyone?",
    "Where is one place you really want to visit and why?",
    "If you want one fictional technology to be real, what would it be? What will you do with it?",
    "Onion rings are now illegal and there is a massive black market trading opeations of onion rings.",
    "Write a diary entry for today.",
    "What are the most romantic things you would like to do?",
    "If you could live inside a fictional universe for the rest of your life, which one will it be and why?",
    "What is one thing you were really afraid of when you were a child but is now no longer afraid of?",
    "Describe one time when you got into really deep trouble.",
    "You now have the superability to walk on water, what will you do?",
    "What/who do you miss the most right now?",
    "Write a diary entry for today.",
    "What is your idea of perfect Valentine?",
    "South Korea has a mandate where every male must serve in the military for at least 2 years, do you think this is right? Why or why not?",
    "What does your dream house look lile?",
    "Should sex education be mandatory in schools?",
    "What is your favourite quote and why is it important to you?",
    "Write a story about how one day you woke up with a tail.",
    "Write a review of the worst movie you have seen.",
    "Which is better, winter or summer?",
    "Do you think sales of human organs should be legal?",
    "Write a diary entry for today.",
    "Write a story that involes these words: Cord, Father-in-law, Grandchild, Pleasure, Steamroller",
    "Should elementary school teach cursive writing? Why or why not?",
    "Write the lyrics to a parody to one of your favourite songs.",
    "If you could have any superpower but you must keep it a secret, what will it be?",
    "Write about 3 places you'd like to travel one day, what do these three places have in common?",
    "Write about one time you felt really happy, what happened? What made you feel happy?",
    "If you're in charge of the world, what would you do to make the world a happier place?",
    "Under what circumstances would you fake your own death?",
    "Imagine that dogs have taken over the world. What do they make the humans do?",
    "Write a diary entry for today.",
    "You are a tree. What is going on in your head as autumn rolls around and you lose all your leaves?",
    "If you had one wish to be granted, what would it be? Be specific, as the genie who grants your wish will attempt to find a loop hole to not get exactly what you want.",
    "What might you do if you can turn invisible at will?",
    "Google, Microsoft and amazon, while advertising their push towards sustainable energy, are inverting machine learning technology to make fossil fuel industries more efficient and produce high throughput, do you think this is ethical?",
    "Do you think it is a human right to carry firearms?",
    "If you could have one fictional or famous person to be your best friend, who would it be and what would you do together?",
    "You are an alien and attempting to communicate with the humans. However the only way you learn how human communicates is using memes.",
    "Write a review of the worst restaurant you have been to.",
    "Write a diary entry for today.",
    "Have you ever lost something that is important to you? Were you able to find it?",
    "Imagine you opened up a store that only sells things that are pink, what do you sell?",
    "Rewrite the ending of your favourite story/book/movie.",
    "Write a story involving the following words: lubricant, cucumber, toilet paper, eggs",
    "What is better, jack of all trades or master of one?",
    "Write about a time when you spilled a secret.",
    "What would you like to learn in the next couple of years?",
    "What is one photograph that has significantly impacted you or is the most memorable to you?",
    "Make up a story that invokes these numbers: 4, 10, 19, 168, 55",
    "What do you think of universal basic income? ",
    "Write a diary entry for today.",
    "What is one thing you really want right now? ",
    "Describe is one time you kept trying and failing but eventually you succeeds.",
    "In 50 years when you’re old, what would be the equivalent saying of “back in my day....” to future generations.",
    "What do you think are some futuristic jobs that doesn’t exist right now ",
    "Take a look at the lyrics of the last song you listened to, make a story out of the last verse in the song.",
    "What is one thing wrong with society today?",
    "Write a diary entry for today.",
    "What is the most memorable moment from your childhood ",
    "If there exists a true gay conversion therapy that actually works, would you partake in it?",
    "What is your wildest sex fantasy?",
    "To what extent should we sacrifice our privacy and freedom for security and stability?",
    "Tell the story of this man (insert image)",
    "Make up a story based on these emojis: 🌻💣🎃🤠.",
    "Describe one time when you were really angry but felt silly afterwards.",
    "Write a diary entry for today.",
    "Describe your morning routine and how could you make it better?",
    "You’re pitching a product to investors. Unfortunately you have no idea what the product does, so you have to bullshit but at the same time make it sound believable.",
    "Would you want to receive 50 more years of lifespan and as a trade, you lose your ability to see?",
    "What is one thing that makes you proud to be a human?",
    "Write a diary entry for today.",
    "One day you go to class, the teacher/professor is not there. All the students seemingly passed out/asleep in the lecture hall. What happened?",
    "Why do you think that clapping has become an almost universal gesture for showing approval or admiration? ",
    "Batteries with extremely large energy density now exists, a smartphone battery could last a whole year. What kind of technology would exist and become applicable because of this?",
    "You’re now a dictator. What laws would you write to ensure that you absolutely stay in power.",
];